### PR TITLE
Update for Shadowlands

### PR DESCRIPTION
**Pull request by yoshimo**
If we touch the TagInfo lines in 679 and following, we access nil values although the debug print works.
If we use the old commented out line, there at least are no more lua errors

### CODE REVIEW

**Comment by Cluuey** [comment]
I was trying to work this out too but I don't understand enough of it to make progress. :-(

I managed to get some initial errors to stop but that lead to errors I'm not equipped to handle.

**Comment by yoshimo** [comment]
Backdrop is pretty straight forward. What i don't understand is the game complaining about indexing nil values in line ~679 when i try to get QuestTagInfo to work.
The correct values are printed immediately after that.

**Comment by xmyno** [comment]
@yoshimo This should be an okay working state for now. Can you please check if PTR and Live are the same and there are no big issues when using this on Live?

**Comment by yoshimo** [comment]
@xmyno i will have a look tomorrow.
Bounties gave me some headache yesterday and i think the SL variables need a bit of tuning.

**Comment by yoshimo** [comment]
The basic stuff works.

- [ ] Unlock conditions for Shadowlands need to be redone
World Quests are available on the following conditions
-  You did your personal covenant quest chain at level 60 and unlocked world quests that way.

- [ ] Night Fae
- [ ] Kyrians
- [ ] Venthyr
- [ ] Necrolords

-  One of your other characters reached 60 and you choose the fast track in Threads of Fate after leaving the maw with level 51

- [x] The Layout is slightly broken
Layout

- [ ] SL Factions need to appear on top of the tooltip

- [x] BFA Factions have missing, aka green icons. Probably RustBolt and Nazjatar

- [ ] Format of the bonus experience currency in SL is wrong

**Comment by xmyno** [comment]
Expansion specific changes will be tracked in #48 
I will merge this now to release a working version for the pre-patch.

**Comment by Cluuey** [comment]
You absolutely rock @xmyno, thanks for making it work even though you're not playing. :-)

Thanks for trying to work it out @yoshimo, it was beyond my ability.

**Pull request merged**
