### PR TITLE
Shadowlands Updates (9.0 - 9.2.5)

### PR DESCRIPTION
**Pull request by Amadeus-**
This is a clean pull request that includes all updates for Shadowlands, including the updates provided by Pull Request https://github.com/xmyno/Broker_WorldQuests/pull/54 by yoshimo.

There is still something funky with the filtering of Cyphers of the First Ones that I'll be working on; otherwise, from my testing this should include most, if not all of the Shadowlands features.

### CODE REVIEW

**Comment by Amadeus-** [comment]
@xmyno Also, if you have decided to abandon World of Warcraft (or this addon), feel free to give me push rights and I'll be happy to take over so as to provide updates for the next expansion.

**Comment by Flawlessa** [comment]
> Also, if you have decided to abandon World of Warcraft (or this addon), feel free to give me push rights and I'll be happy to take over so as to provide updates for the next expansion.

I think he/she may have gone onto something else?  The last update for this project was two years ago, and their other projects also don't appear to have had much work done in a long while too.   Their profile on Curseforge does show a 'last active' ping on Aug. 22, so maybe not totally gone.   But has been quiet. 

It would be nice if this can be properly updated and maintained for 10.0.   It's been a most useful addon, and would be a shame to see it die out.

**Comment by Amadeus-** [comment]
@Flawlessa I'm going to try again to contact @xmyno and see if I can get them to make me a contributor so I can merge pull requests into the original repository here.   If I don't get any response after a while, I'll make another post here letting you know, and then you can follow my fork at https://github.com/Amadeus-/Broker_WorldQuests

I wasn't planning on playing Dragonflight at release; however, I may play just enough to update all my addons.   I will need time to level up to whatever point world quests are unlocked, then I will, at the least, update my fork of this repository.

Either way, keep an eye here on this thread.  I'll update with more information in the coming days/weeks.

====
Edit:  In the meantime, you might use https://github.com/Jartholdy/Broker_WorldQuests as a stopgap measure.

**Comment by Solithe** [comment]
Thank you

**Comment by Amadeus-** [comment]
I have finalized my commits for this pull request and my "Shadowlands1" branch.  I'm now going to merge it to my repository's "Master" branch.    

So, if you want to start using my version of Broker_WorldQuests from this point forward, use https://github.com/Amadeus-/Broker_WorldQuests.

I'm still waiting to hear from the original author on Curseforge.  If I don't hear from him in the next week or so, I'll start a new addon with a new name so that it's available for people to get on CurseForge without having to worry about manual edits, etc.

**Comment by xmyno** [comment]
Hello and sorry for the late response. It is correct that I am no longer playing WoW and have no intention of returning to it. To be honest, I did not expect this addon to still be a thing, since it was quiet here for a long time. But I guess the game just had a long time without much new stuff.

@Amadeus- Thanks for your offer! Developing something that needs access to new content is not really feasible with limited testing capabilities via PTR (if that even is still permanently accessible), so I'll happily hand over further development to you, if you wish to continue this addon. I added you here and on curseforge as contributor.
Creating new version that get uploaded to curse automatically is set up via git tags, but I don't know if that's still working. If you've got any other questions feel free to ask.

**Comment by Solithe** [comment]
There are a lot of fans of your addon and I am very happy to hear that it will be continued with your permission <3

**Comment by Amadeus-** [comment]
@xmyno Thank you so much!   I'll work on figuring out the packaging.  But, as far as updating the code -- I'm going to close this pull request and just do a single pull request that has all of the commits for both Shadowlands and Dragonflight.

**Comment by Amadeus-** [comment]
@xmyno I'm not sure how the packager worked here before.  I tried creating a tag, but nothing happened.   And, making a "release" didn't seem to work either.   The docs for the Bigwigs packager would require that I have admin access on this repo to make adjustments.

I'm also not sure how to get ahold of you ..haha.    If you don't see this, then maybe I'll just adjust Curseforge to use my fork and get the packager working there.

**Comment by Flawlessa** [comment]
Really glad to see the project will continue on with updated contributions.

**Pull request closed without merging**
