### PR TITLE
add filters for Anima containers and soulbind conduits

### PR DESCRIPTION
**Pull request by yoshimo**
This should  allow us to filter anima and conduits as rewards for Shadowland worldquests

### CODE REVIEW

**Comment by Amadeus-** [comment]
I tested this and here are my suggestions/corrections thus far:

**WorldQuests.lua - line 41:**
> I'm not sure offhand what DEBUG does; however, standard practice for release would be to have debugging disabled. So, I'm thinking that should be:  `local DEBUG = false` for the pull request that is implemented.

**WorldQuests.lua - line 141:**
> Add `showAnima = true,` so that it's enabled by default, which matches how other resources, etc. are handled by the addon.

**WorldQuests.lua - line 710:**
> This line should be:  `elseif C_Item.IsAnimaItemByID(itemId) == true then`

**WorldQuests.lua - line 1867:**
> I'm not sure why there is no space between "AnimaItem".  I think it would look better as `{ text = ("|T%s$s:16:16|t Anima Item"):format("1417744"), check = "showAnima" },`
>
> I'm also wondering if there might be a better icon that's used in the game to identify anima. (I'm not sure -- will have to research.)

**Comment by yoshimo** [comment]
DEBUG = true prints chat messages when the addon sees rewards that are not yet handled for example.
It is just an oversight from development on my side.

**Comment by Amadeus-** [comment]
Something happened with this pull request since last night.  It now has commits that go back to 2019, including things that are already in the origin repository.

**Comment by Amadeus-** [comment]
Also, here is a better icon for anima, in my opinion:

`{ text = ("|T%s$s:16:16|t  Anima Item"):format("3528288"), check = "showAnima" },`

**Comment by Amadeus-** [comment]
I created a clean pull request that includes your code as well as additional code I added for Zereth Mortis (WoW 9.2):  https://github.com/xmyno/Broker_WorldQuests/pull/57.   If you're OK with including your pull with mine, you can close this pull request.

**Comment by yoshimo** [comment]
I tried to fix  a mistake I made when I set up the repo and it seems It was quite a few commits ago so it rewrote more  history than I thought

**Comment by Amadeus-** [comment]
> I tried to fix a mistake I made when I set up the repo and it seems It was quite a few commits ago so it rewrote more history than I thought

It's all good.  I made a new pull request that includes your stuff here (and I gave you credit in the pull request comments.)   And, it includes some other things I added for 9.2.5.   So -- if https://github.com/xmyno/Broker_WorldQuests/pull/57 looks good to you -- then you can close this one and xmyno will only see the other one (assuming he comes back.)

I'll update for the next expansion, unless xmyno does it.

**Pull request closed without merging**
